### ISSUE TITLE
[Feature]: Reaktionen für Beiträge

### ISSUE THREAD

**Issue by techotline** [lotta-schule/lotta#130]
### Ticket-Beschreibung

Ziel: Feature für Beitragsseite

Grundidee: **"Bewertungssystem"** und Orientierung an einer **Auswahl an Emojis**, die der Nutzer (Betrachter) als umkommentierte Meinung abgeben darf. Reaktionen sind ein erweiterndes Produkt, um ein kurzes Feedback für seinen Content zu erhalten.

- Autor kann festlegen, ob er die Erfassung der Reaktionen sichtbar sind. Dazu kann er Reaktionen auf seinen Beitrag erlauben oder deaktivieren. (CheckBox im Footer vom Article Edit)

- Darstellung + Übersicht innerhalb des Beitrags / direkt unterhalb von Modul sichtbar (am Ende eines Beitrags)

**Comment by ptitmouton** [comment]
Wäre es nicht einfacher und verständlicher Reaktionen auf Beiträge anzubieten statt auf einzelne Module?

Einer Benachrichtigung per Email klingt nach einer sehr unnötigen Flut an Nachrichten. Ist so eine Benachrichtigungsfunktion überhaupt notwendig?

Denke im ersten Schritt können wir drauf verzichten und es bei einer schlichten Anzeige im Beitrag belassen.

Zur Diskussion möchte ich auch die möglichen Reaktionen "gefällt mir" und "gefällt mir nicht" stellen. Da könnten wir doch etwas expressiver werden?

Ich denke da als Inspiration bspw. an dem was Apple in Messages anbietet:
![download-2](https://github.com/lotta-schule/web/assets/1842883/0174dddb-6b87-4ccd-8117-80c20d54cd00)

Grundätzlich gefällt mir die Idee. 

Weiterer Input? cc @wie0815

**Comment by wie0815** [comment]
Grundsätzlich bin ich für ein Bewertungssystem. Ich fand die Sterne beim MP3 cool und kann mir so etwas vorstellen. In dem Zusammenhang sollten wir darüber nachdenken, ob man Beiträge für Kommentare freigeben kann. Finde ich besser als Sterne.  Beides wäre auch cool.

**Comment by ptitmouton** [comment]
Kommentare sind eine interessante Idee aber nicht Thema des Tickets.

Was wären die Vorteile von Sterne-Bewertungen gegenüber meinen vorgeschlagenen Reaktionen?

Finde Reaktionen besser, da sie deutlich mehr ausdrücken als eine Zahl zwischen 1-5, und ich stehe der Idee von "Bewertung" ehrlich gesagt eher skeptisch gegenüber.

@BillyTheKing wie ist deine Meinung?

Falls Interesse an Kommentarfunktion besteht bitte selbstständig ein Ticket erstellen, dann kann das an entsprechender Stelle diskutiert werden.

**Comment by BillyTheKing** [comment]
Ich bin für eine Mischung. Eine Reaktion per Klick aber ohne 1-5 Sterne sondern nach dem Like Schema, wobei es hier meiner Ansicht nach keine Daumen sein müssen oder Herzen.
Zusätzlich bin ich auch für Kommentare. Hier Stellen sich für mich jedoch noch viele Fragen. Die wir als Team klären sollten.

**Comment by wie0815** [comment]
Ok. Kommentare sind aus der Diskussion raus. Schließe mich der Idee von @ptitmouton an, ähnlich wie es Apple anbietet 3-4 Reaktionen anzubieten. Hier gefällt mir das kreative Symbole angeboten werden wie "Herz", "Klatschen", "Winken" o.ä.
