### ISSUE TITLE
Ändern des Überschriftstyp sollte nach Übernahme Dialog nicht gleich schließen

### ISSUE THREAD

**Issue by techotline** [lotta-schule/lotta#136]
### Bug-Beschreibung

Wenn man einen Beitrag erstellt und das **Titel-Modul** ausgewählt hat, lassen sich über dieses drei unterschiedliche Größen einstellen. Sobald eine Änderung vorgenommen wurde und die Auswahl bestätigt werden möchte bricht das Pop-Up-Fenster automatisch den Vorgang ab, obwohl die Anpassung übernommen wurde. 

Klickweg: Beitrag erstellt -> TITEL -> Moduleinstellungen "Zahnrad"

<img width="1440" alt="Bildschirmfoto 2024-03-02 um 16 05 32" src="https://github.com/lotta-schule/web/assets/153733311/003201c0-272c-4ab1-9a72-040d913cd833">

### Link zur Seite, auf der das Problem aufgefallen ist

unabhängig

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Wenn ich richtig verstehe möchtest du dass man explizit auf OK klicken soll nachdem die Änderung übernommen wurde.

Kann man machen. Ist dann halt ein Klick mehr.
