### ISSUE TITLE
Tab Bar für Author-Tooltip

### ISSUE THREAD

**Issue by BillyTheKing** [lotta-schule/lotta#158]
Für das Tooltip, welches weitere Beiträge eines Autors anzeigt, soll die Navigation der Tabbar aus den Marginalen verwendet werden, um mehrere Autoren und deren Beiträge anzuzeigen. 

Je nach angeklicktem Tab soll der Name des Autors sowie die von ihm verfassten Beiträge angezeigt werden.

**Comment by ptitmouton** [comment]
Ich denke das können wir uns gut für 4.3 vornehmen @BillyTheKing
