### ISSUE TITLE
[Feature]: Eine Kalenderfunktion für Admins integrieren.

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#170]
## Problem

Um Kalender anzubieten sind Nutzer auf externe Dienste mit zweifelhaftem Geschäftsruf gerade im Bereich Datenschutz angewiesen

## Vorschlag

Eine Kalenderfunktion für Lotta sollte integriert werden. Administratoren sollten die Möglichkeit haben, Kalender zu erstellen und ihnen Ereignisse hinzuzufügen.
Die Kalender können dann in einer Marginale angezeigt werden und so für "Gruppen" sichtbar gemacht werden.

In einem weiteren Schritt könnten wir damit eine Bereitstellung im ical-Format ermöglichen, um z.B. die Kalenderadresse intern für Endgeräte bzw. Kalenderabos weiterzugeben. Siehe #231

### Beschreibung

Eine einfache Kalenderoberfläche in Tabellenform wäre sinnvoll.

**Comment by ptitmouton** [comment]
Ich sehe hier (mindestens) zwei Tickets:

Das erste ist das hier. 'Kalender' (faktisch eine Datenstruktur die eine Ansammlung von 'Terminen' beinhaltet) sollen im Adminbereich durch Administratoren angelegt werden können. Termine können dann  erstellten Kalendern zugewiesen werden. 

Diese können dann in einer Kalendermarginale als Quelle eingestellt werden und so angezeigt werden.  

Kalender haben:
- Name
- Termine

Termine haben
- Zusammenfassung
- Beschreibung
- Startzeit
- Endzeit
- Wiederholung

Wenn wir uns am [ical](https://en.wikipedia.org/wiki/ICalendar) Format orientieren möchten (was Sinn ergibt) könnten wir noch etliche weitere Eigenschaften für Termine (wie Ort, Beschäftigt/frei, Anhänge uvm) oder neben Terminen auch andere Inhalte wie TODOs unterstützen, das würde aber vermutlich den Umfang sprengen und könnte später nachgereicht werden wenn notwendig / gewünscht.

Ein Nachfolgeticket wäre die Verfügbarkeit außerhalb von Lotta (zB als .iCal-Datei zum herunterladen oder vermutlich sinnvoller als [CalDAV](https://en.wikipedia.org/wiki/ICalendar)), was jedoch weitere Fragen aufwirft und separat besprochen werden sollte.

Ich schreibe #220 zu letzterem um @wie0815

**Comment by ptitmouton** [comment]
Farben würden weiterhin wie gehabt in der Marginale eingestellt werden. Wüsste erstmal keinen Grund warum wir das ändern sollten, und es würde die Einbindung auch unflexibler gestalten. Oder übersehe ich etwas?

**Comment by wie0815** [comment]
Wenn in einer Oberfläche mehrere Kalender erstellt werden können (Name Kalender, Termine, usw.) finde ich es wichtig, dass man die eingetragenen Termine optisch unterscheiden kann. In der Regel wird das über Farben gelöst. Eine Schule wird mehrere Kalender nutzen wollen (öffentliche Termine, interne Termine usw.).

Wir können über die Einstellungen der Marginalen Farben zuordnen, was sehr gut ist und unbedingt bleiben sollte. Mir geht es um die Nutzung der Kalender durch die Admins. Wenn mehrere Kalender angelegt wurden, sollten die Termine auf den ersten Blick zeigen, welcher Termin zu welchem Kalender gehört. In dem Kontext wären Farben oder Symbole o.ä. sinnvoll.

**Comment by BillyTheKing** [comment]
@wie0815 also zusammengefasst, die Darstellung in der Marginale für alle Nutzer soll so beibehalten werden, korrekt?

**Comment by wie0815** [comment]
Da das iCal-Format keine Farben kennt, sollten eine Lösung finden, das Bearbeiten von Terminen in **nur einer Ansicht** zu umgehen. Vielleicht denken wir darüber nach, ob die Wahl der Farbe für einen Kalender zukünftig in der Kalenderoberfläche zu treffen ist, statt in der Marginalen. Für den Nutzer wäre es wahrscheinlich logischer.
