### ISSUE TITLE
Medienbrowser: Suche implementieren

### ISSUE THREAD

**Issue by ptitmouton** [lotta-schule/lotta#228]
### Bereich

Datei- und Medienverwaltung

### Verhalten

Verhalten

### Problem

Es gibt bisher noch keine Suche für Dateien.
In dem bisherigen (aktuellen bis Lotta v4.2) Medienbrowser hat es einen Filter gegeben, mit dem man die Anzeige der Dateien und Ordner im gerade geöffneten Verzeichnis runterfiltern konnte.

Diese Möglichkeit ist im neuen Design nicht erhalten geblieben und die Mockups von @BillyTheKing  sehen ein echtes Suchfeld vor.

Ich denke eine Suche der Dateien hat einen hohen praktischen Nutzen für eine bestimmte Nutzergruppe (mehr oder weniger "Poweruser" mit vielen Dateien).
Das wird vermutlich vor Allem Schulpersonal betreffen.

### Beschreibung

Die Mockups von @BillyTheKing  ( #213 ) haben eine Suche schon anskizziert. Die Umgestaltung des Medienbrowsers ist ja schon eine Mammut-Aufgabe ohne neue Features einzuführen, deswegen das gesonderte Ticket.

Dass wir seit letztem Jahr auf elasticsearch als gesonderte Suchdatenbank verzichten wird uns die Umsetzung auf Backend-Seite erleichtern. Ich denke nicht dass es besondere Hürden geben würde.

Ich denke aber wir sollten auf Frontend-Seite nochmal über den Entwurf sehen, der sich ja nur sehr vage über eine Suche äußert.
- Wie werden die Suchergebnisse angezeigt?
- Gibt es außer der Volltextsuche weitere Filter-/Suchmöglichkeiten?
- Wie ist der Übergang von "Dateisystem erkunden" → Suche → Suchergebnisse → zurück zur "normalen" Ansicht? Funktioniert das auch auf kleinen Bildschirmen? (Hier mussten kleine Bildschirme ja schon Kompromisse eingehen)
- Wird die Suche auch in den Auswahl-Modi (Einfach-Auswahl als auch Mehrfach-Auswahl) der Dateiverwaltung angeboten? Ich denke gerade dort würde sie sich als praktisch erweisen. Lässt sich das ohne weiteres vom Bedienkonzept übertragen?

Ich würde @BillyTheKing hier zuerst den Ball zuspielen falls wir das umsetzen möchten.

**Comment by BillyTheKing** [comment]
Web:
1) Eingabe Schlagwort in die Suchleiste -> Suchleiste verbreitert sich, Navigationsbuttons werden ausgegraut, Upload-Buttons werden ausgegraut
2) Anzeige von Suchergebnissen aufgeteilt nach Dateien & Ordnern
3) Auswahl einer Datei/eines Ordners zeigt Vorschau an + Navigation im Footer des Browsers zeigt an, in welchem Ordner/Überordner sich die ausgewählte Datei/der ausgewählte Ordner befindet -> anklickbar, man gelangt in die reguläre Medienbrowser Ansicht

![Image](https://github.com/user-attachments/assets/7dc2b17c-0478-4171-bfaf-de0c5ee8dca2)

Mobil:


![Image](https://github.com/user-attachments/assets/131f215f-06b3-4bec-b91f-60ffe78d5d9d)

**Comment by ptitmouton** [comment]
@wie0815 schlägt vor, den Button ‚Anzeigen‘ in der Suche in ‚zur Datei gehen‘ umzubenennen. 

Meinungen @BillyTheKing ?

Ich persönlich habe da keine starke Meinung, würde aber den Text gerne kürzen und schlage vor: ‚zur Datei‘

**Comment by ptitmouton** [comment]
@wie0815 du hattest 5 Punkte aufgezählt aber wenn ich den Text richtig verstanden gabelst das der einzige Vorschlag?

**Comment by BillyTheKing** [comment]
> @wie0815 schlägt vor, den Button ‚Anzeigen‘ in der Suche in ‚zur Datei gehen‘ umzubenennen.
> 
> Meinungen @BillyTheKing ?
> 
> Ich persönlich habe da keine starke Meinung, würde aber den Text gerne kürzen und schlage vor: ‚zur Datei‘

"Zur Datei" ist für mich fein.
