### ISSUE TITLE
Nachrichten: Autofocus in Nachrichteneingabe entfernen, virtuelles Keyboard stört auf mobilen Geräten

### ISSUE THREAD

**Issue by techotline** [lotta-schule/lotta#235]
### Bereich

Nachrichten (inkl. "Meine Beiträge")

### Verhalten

Verhalten

### Problem

Es ist frustrierend, wenn auf dem iPhone ein Chat ausgewählt und angenommen wird, dass in diesem Moment auch eine Nachricht verfasst wird, obwohl (neue) Nachrichten nur gelesen werden möchten. Der Cursor befindet sich im Eingabefeld, das zunächst mit "Fertig" bestätigt werden muss, um A) die Tastatur auszublenden und B) in die Lese-Ansicht zu gelangen.

Safari:

![nachrichten-autostopCursor](https://github.com/lotta-schule/web/assets/153733311/51589982-bedf-4c30-81f0-b0fac868a6e9)

Firefox:

![Firefox-Nachrichten](https://github.com/lotta-schule/web/assets/153733311/328eb5e1-6fc4-4d69-9bd2-0c481bcf4358)

Das ist sicherlich kein Bug, sondern müsste als neues Feature umgesetzt werden.

### Beschreibung

Wenn ein Chat geöffnet wird, sollte das Eingabefeld deaktiviert sein, bis der Cursor gesetzt wird.

**Comment by ptitmouton** [comment]
Bin grundsätzlich einverstanden. Auch wenn's für Nutzer mit Tastatur wiederum ziemlich nervig ist, den Focus nicht an der gerade relevanten Stelle gelegt zu bekommen.
Autofocus ist eigentlich ein Accessibility-Feature und es ist echt kacke, dass es keine API gibt um zu erkennen ob eine Hardware-Tastatur am Gerät angeschlossen ist.

Möglichkeiten wären hier

- Autofocus für alle ausschalten
- Autofocus per UA-Sniffing nur für mobile Geräte ausschalten (unzuverlässig)
- Autofocus per Bildschirmgröße nur für mobile Geräte ausschalten (unzuverlässig)

Ich recherchier mal ob ich was besseres finde.
Wenn nicht werde ich es vermutlich für alle rausnehmen.
