### ISSUE TITLE
Beitragsansicht - "weitere Beiträge zu ...": Lange Tags brechen aus Layout aus

### ISSUE THREAD

**Issue by techotline** [lotta-schule/lotta#236]
### Bug-Beschreibung

VORABINFORMATIONEN

- getestet mit iOS / MacOS / iPadOS
- Bug-Report für mobil-view
- in den Browsern Safari, Firefox festgestellt (Mutmassung: ist nicht vom Browser abhängig)

User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Mobile/15E148 Safari/604.1
Platform: iPhone
Screen: 393x852
Window: 393x660
DevicePixelRatio: 3
DeviceOrientation: portrait-primary

**Folgender Fall**

Ein Nutzer hat einen Artikel erstellt und einen beliebigen Tag hinzugefügt, der eine markante Anzahl an Buchstaben und Zeichen besitzt. Weil der Header für 'weitere' Beiträge beschränkt ist, bricht dieser offensichtlich aus seinem Layer aus.
Tags sollten demzufolge im UI _umgebrochen_ (mgl. Variante) werden, wenn sie zu lang sind bzw. eine bestimmte Anzahl an Zeichen erreicht haben, um weiterhin ein nutzerfreundliches UX zu gewährleisten. 

![Bug-Tags_2](https://github.com/lotta-schule/web/assets/153733311/af082ec8-2b78-4136-80bc-84e48f999f35)
![Bug-Tags](https://github.com/lotta-schule/web/assets/153733311/247941d4-f6ee-45c9-975d-1de56d4e0d80)

### Link zur Seite, auf der das Problem aufgefallen ist

https://schule-am-buergergarten-eilenburg.lotta.schule/a/459-Teilnahme-am-sachsischen-Informatikwettbewerb-2024

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by BillyTheKing** [comment]
> wird in separatem Ticket gelöst: #252

**Comment by ptitmouton** [comment]
Moment mal ich dachte #252 wird eine zusätzliche Maßnahme, damit wir verhindern, dass die Nutzer nicht in Längenbeschränkungen kommen.

Habe es nicht als Ersatz gesehen.

Ich denke wir sollten trotzdem die Länge der Tags beschränken oder umbrechen oder beides. Das Problem besteht ja noch immer, nur halt nicht wenn man "#" zwischendurch schreibt @BillyTheKing

**Comment by ptitmouton** [comment]
Ich löse dass so **dass** ich lange Tags umbreche @BillyTheKing 

#252 soll davon unberührt werden und ist weiter geplant
