### ISSUE TITLE
[Staging]: Adminbereich: Subkategorien können nicht mehr ausgewählt werden; System reagiert nicht auf Anfrage

### ISSUE THREAD

**Issue by techotline** [lotta-schule/lotta#278]
### Bug-Beschreibung

Möchte man die **Subkategorie** seines Lottas bearbeiten und ggf. eine Umstrukturierung vornehmen, sind die Elemente der Liste nur passiv verfügbar, weil **Änderungen nicht möglich** sind. 

Die höchste Ebene (Hauptnavigation) bleibt davon unberührt. Ihre Konfiguration kann bedenkenlos gespeichert werden.

Browser: getestet mit Safari, Firefox
Gerät: MacBook 13"
Betriebssystem: MacOS

Visualisierung:

<img width="1250" alt="24-07-Subkategorien_edit" src="https://github.com/user-attachments/assets/82c409b8-6214-4ffd-80fd-c1e075625696">

### Link zur Seite, auf der das Problem aufgefallen ist

*.staging.lotta.schule

### Gerätekategorie

Trifft hier nicht zu.

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Problem wird mit #274 gelöst (siehe https://github.com/lotta-schule/lotta/commit/797826b4ce6b299d2ce4f716010c4935d92f286f )
