### ISSUE TITLE
Auswahlfenster Nutzersuche Adminbereich abgeschnitten

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#281]
### Bug-Beschreibung

Sucht man im Admin-Bereich einen Nutzer und möchte die Filter nutzen, wird das Pop-Up Fenster nicht korrekt dargestellt und abgeschnitten (vgl. Bildschirmfoto). Dadurch ist das Scrollen im Fenster bei vielen Gruppen umständlich.
Der Fehler tritt nur am Beginn des Dialoges auf, d.h. sobald man eine Auswahl getroffen hat und es werden Nutzer aufgelistet, öffnet das Pop-Up-Fenster korrekt. Auch beim Fenster "Zuletzt angemeldet" ist der Darstellungfehler sichtbar.
![Bildschirmfoto 2024-07-18 um 09 24 47](https://github.com/user-attachments/assets/09797ba8-0929-4518-bdfa-cdb3dc631d78)

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg.staging.lotta.schule/admin/users

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Ist derselbe Safari-Bug wie #148
