### ISSUE TITLE
Adminbereich: Kategorien können mit kleinen Bildschirmen nicht bearbeitet werden (mobil)

### ISSUE THREAD

**Issue by techotline** [lotta-schule/lotta#300]
### Bug-Beschreibung

Ich möchte mit meinem mobilen Endgerät eine Kategorie (oder Subkategorie) anklicken und gewisse Änderungen vornehmen. Dies ist momentan leider nicht möglich; mein Dialog reagiert nicht.

(getestet mit iPhone 14 Pro)

### Link zur Seite, auf der das Problem aufgefallen ist

recordz.staging.lotta.schule

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

### In welchem Browser ist das Problem aufgetreten

Firefox, Safari

**Comment by ptitmouton** [comment]
Bitte in Zukunft wirklich mal die Felder ernsthaft ausfüllen, '*.staging.lotta.schule' ist keine URL. Wenn ich nicht zufällig wüsste welches Problem du beschreibst, würde ich das vermutlich nur aus der Beschreibung hier nicht herauslesen können.

Es muss bei weitem nicht immer ein Bild dabei sein, aber mindestens der Pfad, besser noch die komplette URL und eine konkrete Handlungsanweisung zum Reproduzieren erleichtern mir ungemein die Arbeit!


Das Problem selbst ist vermutlich dasselbe wie bei #301 und sollte in #296 gelöst sein. 

/close
