### ISSUE TITLE
[Bug]: Navigation: Beitrag erstellen nicht möglich

### ISSUE THREAD

**Issue by techotline** [lotta-schule/lotta#301]
### Bug-Beschreibung

Ich möchte einen neuen Beitrag für meine Homepage anlegen. Ich könnte den dazugehörigen Button unendlich anklicken, ohne das er reagiert.

**Betrifft iPad Bildschirmgrößen / Desktop**; mobile Endgeräte sind von dieser funktionalen Einschränkung ausgenommen.

### Link zur Seite, auf der das Problem aufgefallen ist

*.staging.lotta.schule

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Firefox, Safari

**Comment by ptitmouton** [comment]
Ist schon in #296 gelöst, ist nur noch nicht auf Staging
