### ISSUE TITLE
Adminbereich: Darstellung: Absturz nach Auswahl einer Schriftart

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#313]
### Bug-Beschreibung

Neues Lotta angelegt - im Admin-Bereich: Darstellung - Schriften z.B. für Überschrift - Klick in das Feld: "Bitte wählen" für zur Fehlermeldung: **Application error: a client-side exception has occurred (see the browser console for more information).**

### Link zur Seite, auf der das Problem aufgefallen ist

https://ttt.staging.lotta.schule/admin/presentation

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Problem betrifft nur den Prod-Build und scheint mit dem SSR der Select-Box zusammenzuhängen

<img width="285" alt="Screenshot 2024-08-25 at 22 52 52" src="https://github.com/user-attachments/assets/1689c857-f8ae-4b6a-873b-c544aad1b3b1">
