### ISSUE TITLE
Adminbereich: Absturz bei Bestätigung im Dateiauswahldialog

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#314]
### Bug-Beschreibung

Habe über den Medienbrowser eine Datei hochgeladen. Das funktionierte nur per Drag & Drop. Wählt man eine Datei aus und möchte so den Upload starten, reagiert das System nicht:

### Link zur Seite, auf der das Problem aufgefallen ist

https://ttt.staging.lotta.schule

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Duplikat von #314
