### ISSUE TITLE
[Bug]: Logo in Grundeinstellungen lässt sich nicht ändern

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#315]
### Bug-Beschreibung

Im Admin-Bereich: Grundeinstellungen covert man über das Feld "Logo" - es erscheint der Button "Logo ändern" - Klickt man öffnet sich der Medienbrowser - wählt man ein Bild aus (Klick aufs Bild) meldet das System: Application error: a client-side exception has occurred (see the browser console for more information).

### Link zur Seite, auf der das Problem aufgefallen ist

https://ttt.staging.lotta.schule/admin/general

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Duplikat von #314
