### ISSUE TITLE
[Bug]: Öffnen der Beitrag-Bearbeiten-Seite nicht möglich

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#317]
### Bug-Beschreibung

Das Bearbeiten von Beiträgen ist nicht möglich. Der Klick auf den Stift (Bearbeitungsmodus) führt (nachdem der Bildschirm kurz zuckt) zu folgender Fehlermeldung: Application error: a client-side exception has occurred (see the browser console for more information).

### Link zur Seite, auf der das Problem aufgefallen ist

https://ttt.staging.lotta.schule/a/3-Willkommen/edit

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Das ist dasselbe Problem wie bei #316 

Es gibt einen Fehler beim Abruf der Nutzergruppen.

**Comment by ptitmouton** [comment]
Hatte das Ticket aus Versehen neu geöffnet, es sollte als Duplikat geschlossen bleiben.

Relevante Diskussion hierfür findet in #316 statt
