### ISSUE TITLE
Button für "Beitrag erstellen" über Nutzernavigation für Desktop reagiert nicht

### ISSUE THREAD

**Issue by techotline** [lotta-schule/lotta#322]
### Bug-Beschreibung

Klickt man auf dem Button 'Beitrag erstellen' in der Nutzernavigation (ausschließlich Desktop), passiert nichts. Ich würde erwarten, dass sich der Dialog "Beitrag erstellen" öffnet, in dem ich einen neuen Beitrag erstellen kann.

Wechsle ich direkt danach die Seite (zB eine andere Kategorie), öffnet sich der Dialog, ohne dass ich den Button nochmal anklicke.

### Link zur Seite, auf der das Problem aufgefallen ist

https://ttt.staging.lotta.schule

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Firefox, Chrome (Edge, Opera, ... ), Safari

**Comment by ptitmouton** [comment]
Problem besteht seit 6828d9cebc09b0759a1c0c06a5cdac3be8fc7b34
