### ISSUE TITLE
[Feature]: Kategorie auf Subkategorie weiterleiten AUSWAHLFENSTER - Anzeige verbessern

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#324]
### Bereich

Kategorie-Seite (inkl. Startseite)

### Verhalten

Aussehen / Design

### Problem

Möchte man eine Kategorie auf eine andere Kategorie weiterleiten, kann man die Kategorie in einem Pop-Up Fenster wählen. Hier wäre es sinnvoll, die Struktur des Lotta Projektes anzuzeigen. Derzeit werden die Kategorien ungeordnet angezeigt. Vgl. Bildschirmfoto.
 
<img width="870" alt="Bildschirmfoto 2024-08-26 um 21 12 52" src="https://github.com/user-attachments/assets/b59dd0bd-3caf-479f-8f1b-f1fc749cb5af">

### Beschreibung

Besser: linksbündig die Kategorie und darunter etwas eingerückt die Subkategorien.

**Comment by ptitmouton** [comment]
Duplikat von #72
