### ISSUE TITLE
Adminbereich: Neuer Medienbrowser: Dateien lassen sich nicht hochladen

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#329]
### Bug-Beschreibung

Nach dem Klick auf die "Wolke" (Upload-Symbol) öffnet sich das Browserfenster des Computers und man kann ein Bild auswählen. Nach dem Klick auf "Hochladen" passiert jedoch nichts.

### Link zur Seite, auf der das Problem aufgefallen ist

https://ttt.staging.lotta.schule/admin/categories/7

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by wie0815** [comment]
Geht man über "Meine Dateien und Medien" im individuellem Menü, funktioniert der Upload. ... nur nicht über den Dialog im Admin-Bereich.

**Comment by wie0815** [comment]
@ptitmouton Das Gild für alle Dialoge im Admin-Bereich. Ein Hintergrundbild lässt sich auch nicht hochladen, geht man über den Menüpunkt "Darstellung" im Admin-Bereich.

**Comment by ptitmouton** [comment]
Das Problem ist hier dass der neue ApolloClient den Request nicht korrekt als `FormData` verschickt.

Ich weiß noch nicht genau warum, sehe ich mir morgen an.

**Comment by wie0815** [comment]
@ptitmouton: Der Medienbrowser, der sich im Dialog öffnet sieht auch anders aus, als der Medienbrowser, den man ausgeliefert bekommt, wenn man "Meine Dateien und Medien" öffnet. Es fehlt bei mir z.B. ein Upload-Button (siehe Foto).
<img width="1093" alt="Bildschirmfoto 2024-08-28 um 20 01 53" src="https://github.com/user-attachments/assets/cf7a01ab-76cc-4b86-9637-8113e1183c36">
