### ISSUE TITLE
Select-Komponente: öffnet sich das Menü eines Select-Feldes am unteren Bildschirmrand, kann es über den Viewport hinausgehen und eine Auswahl verunmöglichen

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#330]
### Bug-Beschreibung

Möchte man als Admin eine Schriftart wählen, öffnet sich das Pop-Up-Fenster und verschwindet am unteren Fensterrand (je nach Bildschirm). Unter Umständen lässt sich keine Auswahl treffen. (vgl Video)

https://github.com/user-attachments/assets/efc09fbf-b2d6-46f8-b19c-bb95a7847a12

### Link zur Seite, auf der das Problem aufgefallen ist

https://ttt.staging.lotta.schule/admin/presentation

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Das Problem tritt ausschließlich auf wenn der Bildschirmplatz zum Ausweichen nach oben nicht genug Platz hat.

Ich denke die sinnvollste Lösung ist hier die Beschränkung des Select-Popups in der Höhe

**Comment by wie0815** [comment]
👍
