### ISSUE TITLE
[Bug]: Admin-Bereich: Nutzerverwaltung - Filter: Anzeige fehlerhaft

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#333]
### Bug-Beschreibung

In der Admin-Oberfläche kann man "Nutzer Suchen". Man hat zwei Filter zur Auswahl: "Gruppe" und "Besuche". Möchte man den Filter nutzen, wird dieser beim Aufpoppen durch ein anderes Designelement verdeckt. Eine Auswahl ist nicht möglich. Siehe Bildschirmfotos.
<img width="397" alt="Bildschirmfoto 2024-08-28 um 16 23 32" src="https://github.com/user-attachments/assets/a4239224-c74f-4e02-9c3f-9c48f4902e18">
<img width="499" alt="Bildschirmfoto 2024-08-28 um 16 23 48" src="https://github.com/user-attachments/assets/21691e90-b122-455f-a30d-e854e91f679d">

### Link zur Seite, auf der das Problem aufgefallen ist

https://ttt.staging.lotta.schule/admin/users

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Das ist ein bekannter Safaribug und schon in #148 beschrieben
