### ISSUE TITLE
[Bug]: Scrollen im Admin-Bereich nicht mehr möglich

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#346]
### Bug-Beschreibung

Nach den letzten Verbesserungen ist ein neuer Bug entstanden. Im Admin.Bereich kann man nicht mehr scrollen. Bereich Darstellung: Schriftauswahl ist nur erreichbar, wenn man nach unten scrollt. Das geht jedoch nicht.

### Link zur Seite, auf der das Problem aufgefallen ist

https://ttt.staging.lotta.schule/admin/presentation

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Ja, das Problem ist #333 , Safari bereitet uns hier einige Kopfschmerzen

**Comment by ptitmouton** [comment]
Mit #347 geschlossen
