### ISSUE TITLE
[Bug]: Kalendereinträge in der Kalenderoberfläche nicht sichtbar

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#350]
### Bug-Beschreibung

Ich habe für die Genossenschaft Kalender erstellt. In der Kalenderoberfläche habe ich einen Termin gesetzt im Monat Oktober (23.10.2024 um 15.00 bis 16.30) im Kalender "iL agil". In der Kalenderansicht wird der Termin nicht angezeigt, ist aber gespeichert.

In der Marginalen wird der Kalender jedoch korrekt angezeigt. Siehe: https://inklusivleben.jetzt/c/51-iL-agil

### Link zur Seite, auf der das Problem aufgefallen ist

https://inklusivleben.jetzt/admin/calendars

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by wie0815** [comment]
Da ich den Eintrag 2x vorgenommen habe, ist der Termin 2x da. Jedoch kann ich ihn nicht löschen.

**Comment by ptitmouton** [comment]
Ja es werden momentan nur Termine des aktuellen Monats geladen, ist mir vorhin auch schon aufgefallen
