### ISSUE TITLE
[Bug]: Fehlercode 502, nachdem sich Nutzer angemeldet hat

### ISSUE THREAD

**Issue by techotline** [lotta-schule/lotta#353]
### Bug-Beschreibung

Zunächst löschte ich alle Cookies, Websitedaten (inkl. Cache) und den Verlauf meines Browsers vollständig. Des Weiteren habe ich den jeweiligen Browser geschlossen und die Application neu gestartet. Bin ich bei **Ehrenberg** unangemeldet als Gast (Besucher) auf der Seite, ist alles in Ordnung und Lotta lässt mich als Betrachter soweit alle Inhalte einsehen. Möchte ich mich jedoch anmelden bzw. ich habe mich erfolgreich mit meinem Benutzerkonto angemeldet und möchte im Anschluss einen Beitrag ansehen, erscheint folgende Fehlermeldung:

<img width="1469" alt="502nginx" src="https://github.com/user-attachments/assets/7ec1e641-97d4-4edf-83fe-83148fbe1615">

INFORMATIONEN ÜBER MEIN SYSTEM

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Platform: MacIntel
Screen: 1470x956
Window: 1470x839
DevicePixelRatio: 2
DeviceOrientation: landscape-primary

@ptitmouton 

Folgendes war jedoch möglich: Man hat ein neues Benutzerkonto registriert und weniger Einschreibeschlüssel in seinem Profil eingegeben. Mutmaßlich könnte es damit zusammenhängen, dass die Seite abstürzt, weil ich unzählige Einschreibschl. hinterlegt habe.

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/a/4955-Juniorwahl-Landtagswahl-in-der-Schule-ERGEBNISSE

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Firefox, Safari

**Comment by ptitmouton** [comment]
Ja die Datenbank läuft gerade etwas am Limit was die Connections angeht.

Ich vergrößere den Connection Pool, ist aber eine Infrastrukturfrage und ist von diesem Repo erstmal unabhängig.

**Comment by ptitmouton** [comment]
Upsi mir ist bei der Gelegenheit aufgefallen dass mir wohl irgendwann mal ein Fehlerchen untergelaufen ist und ich den Sandbox-Adapter aus Versehen nicht nur für Test, sondern für alle Umgebungen eingesetzt habe ...

Hatte mich schon gewundert warum ich noch immer so viele 502er sehe ....

**Comment by ptitmouton** [comment]
Das Problem besteht seit 031b0ad317058de1508c56e2efe417edd3037b3d .. 
Vermutlich also seit 4.2.0

**Comment by ptitmouton** [comment]
Ja bin dran

**Comment by ptitmouton** [comment]
Zur Referenz: Das Problem waren zu große Header für die Default-Buffer-Größe von nginx.

Sollte das Problem auftreten sollte die Seite hier hilfreich sein:
https://www.getpagespeed.com/server-setup/nginx/tuning-proxy_buffer_size-in-nginx
