### ISSUE TITLE
[Bug]: Nachrichtensystem meldet Fehler.

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#354]
### Bug-Beschreibung

Die Nachricht erreichte mich aus Chemnitz. Die Infos sind dürftig und ich hoffe, dass @ptitmouton etwas damit anfangen kann:
Die Schulleiterin der Kooperationsschule hat sich erfolgreich mit den Browsern "edge" und "Firefox" bei ihrem Lotta angemeldet. Wenn Sie 
auf "Nachrichten" klickt erscheinen folgende Fehlermeldungen im Browserfenster:
<img width="956" alt="Screenshot 2024-09-01 184952" src="https://github.com/user-attachments/assets/61aede4e-1da6-44ac-b1b8-1cb519b6f6c4">
<img width="918" alt="Screenshot 2024-09-01 185147" src="https://github.com/user-attachments/assets/825d859d-0c48-443c-83c5-479f12091bbe">
Bild oben Firefox, Bild unten Edge

### Link zur Seite, auf der das Problem aufgefallen ist

https://kooperationsschule-chemnitz.org

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Firefox

**Comment by ptitmouton** [comment]
Siehe #353
