### ISSUE TITLE
[Bug]: Darstellung des Auswahlmenüs in Statistiken verbessern

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#357]
### Bug-Beschreibung

Im Bereich Statistiken kann man filtern. Das Auswahlfenster poppt nach unten auf und "verschwindet" teilweise am linken Rand (vgl. Bildschirmfoto). Der Fehler ist in allen Lottas sichtbar.
<img width="545" alt="Bildschirmfoto 2024-09-02 um 07 00 37" src="https://github.com/user-attachments/assets/161299a1-18e3-416a-a951-ae382b6e56fd">

### Link zur Seite, auf der das Problem aufgefallen ist

https://inklusivleben.jetzt/admin/analytics

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Schon gemeldet (2x)
Siehe #148 oder zB #333
