### ISSUE TITLE
Vorschlag: Im Bearbeitungsmodus sollten Rahmen und Toolbar von Modulen immer sichtbar sein

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#358]
Wählt man bei der Beitragseinstellung ein Modul aus, wird der Rahmen des Moduls erst sichtbar, wenn man darüber hovert. Das führt nachweislich dazu, dass unerfahrene Nutzer mehrere Module ohne Inhalt erstellen. Vorschlag: Die Rahmen der Module bekommen eine hohe Transparenz von ca.80%. Ich bin auch dafür Module ohne Inhalt in fertigen Beiträgen sichtbar zu machen. Dadurch lernen die Nutzer schnell.

**Comment by ptitmouton** [comment]
#246 hat damit mMn nichts zu tun

Mir ist es egal, aber ein Bisschen kommt mir der Vorschlag "wieder sichtbar machen" etwas "faul" vor.

Diskussion sollte mit @BillyTheKing geführt werden, kommt mir aber so vor als gäbe es diverse Möglichkeiten das beschriebene Problem zu umgehen, zB den Rahmen bei gerade erst erstellten Modulen anzuzeigen.

**Comment by BillyTheKing** [comment]
Habe eine Lösung eingepflegt.
