### ISSUE TITLE
[Bug]: Fehler 401

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#367]
### Bug-Beschreibung

"Name" und "Beschreibung" von Ereignissen im Kalender kann zur Fehlermeldung 401 führen wenn div. Sonderzeichen genutzt werden.
Bsp. Notenschluss 12/1 führt zur Fehlermeldung

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/admin/calendars

### Gerätekategorie

Trifft hier nicht zu

**Comment by ptitmouton** [comment]
Wann solle es zum Fehler 401 kommen? Beim Erstellen eines Ereignisses? Beim speichern? Ist der Fehler wirklich reproduzierbar?

Eine Verbindung von 401 zum Kalender kommt mir da gerade etwas unwahrscheinlich vor (lass mich bei genauer Fehlerbeshreibung eines besseren belehren).

Eventuell haben wir allgemein ein Problem mit auslaufenden Tokens.

**Comment by ptitmouton** [comment]
Ich habe ein Problem gefunden das eventuell das hier besprochene mit abdecken würde.

Das ist aufgrund der sehr schlechten Ticket-Qualität schwer zu sagen.
Ich vermute das hier beschriebene Szenario ist nicht mal auch nur ein weiteres Mal zur Kontrolle ausgeführt worden?

Ich konnte das Problem so weder im Admin-Bereich, noch beim Abruf der der Termine über die Marginale noch beim Abruf der ics-Datei, mit verschiedenen Nutzern und Konstellationen, nachstellen. 

Allerdings ist mir schon länger aufgefallen dass die Anwendung recht häufig einen 401 zurückbekommt.
Mir ist eine Stelle aufgefallen bei der client-seitig der Access-Token nicht korrekt erneuert wird. Ist die Seite länger als 20 Minuten lang offen, ohne dass ein harter Seitenwechsel / Refresh passiert ist, läuft der Token aus.

Das Problem wird in #375 angegangen.

Dieses Ticket hier schließe ich erstmal. Es ist etwas irreführend und ich rechne auch nicht mehr mit einer Antwort.

Sollte doch ein reproduzierbarer Fall konstruiert werden können gerne wieder aufmachen.
