### ISSUE TITLE
Beitrag: "Reaktionen" von nicht-angemeldeten Nutzern sollte nicht möglich sein

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#368]
"Reaktionen" auf Beiträge werden auch für nicht-angemeldete Nutzer angezeigt.

## Aktuelles Verhalten

Für nicht angemeldete Nutzer gilt:

- Erstellt der Nutzer eine Reaktion, passiert augenscheinlich nichts
- Klickt der Nutzer auf eine vergebene Reaktion (bsp. [🌶️ 3]) wird kurz das Popup mit den Reaktionen angezeigt. Danach meldet Lotta: Application error: a client-side exception has occurred (see the browser console for more information).

## Vorgeschlagene Lösung

- Der Button zum Erstellen von Reaktionen sollte für nicht angemeldete Nutzer nicht sichtbar sein
- Nicht angemeldete Nutzer sollten nur die Anzahl der Reaktionen sehen können. Nicht wer reagiert hat. DIe Buttons für vergebene Reaktionen sollten ohne Funktion sein

**Comment by ptitmouton** [comment]
Finde man kann darüber streiten wie sehr das wirklich ein Bug im engsten Sinne ist, aber da wir anscheinend eh entschieden haben noch ein paar Verbesserungen die genau genommen nicht unbedingt als Hotfix veröffentlicht werden müssten als Patch nachzureichen würde ich das gleich mit übernehmen.
