### ISSUE TITLE
Kalender: Funktion einführen, die das anzeigen weiterer Termine an einem Tag ermöglicht

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#369]
### Bug-Beschreibung

Trägt man mehrere Termine an einem Tag in den Kalender ein, werden ab einem bestimmten Termin die Einträge nicht mehr korrekt angezeigt. Das Bearbeiten der Termine, die schon gesetzt wurden ist dadurch nicht mehr möglich. Das Problem ergibt sich aus der Bildschirmgröße, d.h. kleine Bildschirme zeigen u.U. max. 2 Termine korrekt an. Der dritte Termin "verschwindet" am unteren Rand. Nachvollziehbar wird das Phänomen, wenn man das Fenster kleiner zieht.

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/admin/calendars

### Gerätekategorie

Trifft hier nicht zu

**Comment by ptitmouton** [comment]
Das ist kein Bug, das ist noch nicht umgesetzt gewesen.
Ich hatte schon überlegt, ob es nicht sinnvoll wäre, ein "Beta"-Label o.ä. an die Kalenderfunktion zu packen; Ich bin mir nicht sicher ob wir klar genug kommuniziert haben, dass wir erstmal nur eine Minimalfassung veröffentlichen und von da aus weiterarbeiten wollen.

Grundsätzlich wird das Klein- und Großschieben das Fensters im Admin-Bereich zum neu rendern der Einträge in einer Zelle des Kalenders nicht unterstützt, und ich sehe da auch kurzfristig keine notwendigkeit für.

Was eine noch fehlende Funktion "weitere Termine anzeigen" angeht:
Da wir anscheinend eh schon über Bugfixes hinaus ein Patch für 5.0.0 veröffentlichen wollen, lasse ich mich dazu breitschlagen mir hier **eine einfache Lösung** zu überlegen.
Ich wäre aber sehr angetan wenn wir jetzt hier nicht vorn und hinten schnelle Lösungen an den Kalender flicken, nur weil gerade jemand irgendetwas braucht.
Wir sollten Feature-Wünsche sammeln und uns konzeptionell und gestalterisch (cc @BillyTheKing ) überlegen wie das am Besten umzusetzen ist, und das dann ordentlich in einem nächsten geplanten Update ausliefern.

**Comment by wie0815** [comment]
Vielleicht ist ein "Beta"-Symbol sinnvoll?
