### ISSUE TITLE
[Bug]: Klick auf eine Kategorie mit interner Weiterleitung nach altem Schema führt zur Fehlermeldung "Es gibt kein Lotta unter dieser Adresse"

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#391]
### Bug-Beschreibung

Klickt man auf eine Kategorie in einem Lotta, kann es passieren, dass der Fehler angezeigt wird. Das Problem besteht darin, dass der Fehler azyklisch auftritt. Er wurde aus Chemnitz, Radefeld und Delitzsch gemeldet. Ich selbst habe verschiedene Lottas besucht und mich durch  das Menü geklickt um das Fehlerbild zu "erhaschen". Auch bei mir ist er immer mal wieder aufgetreten (vgl. Bildschirmfoto).

Läd man die Seite neu, wird sie in der Regel korrekt geladen. In Radefeld jedoch ist auffällig, dass die Kategorien (rechts im Menü), die in der Regel nicht so oft besucht werden, den Fehler öfter zeigen und die Startseite z.B. nie betroffen ist. Hinzu kommt, dass u.U. auch das Neuladen der Seite nicht zur korrekten Darstellung der Seite führt.
<img width="1101" alt="fehler" src="https://github.com/user-attachments/assets/49680778-e86b-491a-8b3d-3a2c95712ebe">

### Link zur Seite, auf der das Problem aufgefallen ist

nicht möglich (vgl. Beschreibung!)

### Gerätekategorie

Trifft hier nicht zu

**Comment by ptitmouton** [comment]
Ein kompletter, unabgeschnittener Screenshot, der neben der (Achtung Überraschende Bitte) vollständigen Adresse auch Datum und Uhrzeit einer beispielhaften Fehlermeldung zeigen würde wäre extrem hilfreich.

Sehr eventuell käme [dieser Sentry-Fehler](https://lotta.sentry.io/issues/5790759905/?project=1517545&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=3) in Frage, aber das ist gerade bei der sehr dünnen Informationslage sehr schwer zu sagen.

Ich denke ohne das Problem nachzustellen kommen wir hier nicht weiter, ein Problem mit dem Auth-Token könnte aber durch das unregelmäßige Auftreten des Fehlers augenscheinlich ausschließlich bei nicht als erstes aufgerufenen Seiten eine plausible erste Schätzung.

Ist ein Auftreten des Problems bei unangemeldeten Nutzern bekannt?

**Comment by ptitmouton** [comment]
Die oben erwähnte Vermutung hat sich bestätigt.
Genau weiß ich noch nicht warum, aber es werden ungültige Anmelde-Token gemeldet.
Ich seh mir das weiter an.

**Comment by ptitmouton** [comment]
Also ich muss mich soweit ich mit den vorhandenen Informationen das Problem richtig erfasst habe korrigieren.
Ich konnte den Fehler bei Ehrenberg nachstellen, bei einer einzigen Kategorie (53-Galerien). Diese hatte noch eine interne Weiterleitung auf das alte Link-Schema `/categories/<id>-<slug>` benutzt. Mit dem Umstellen auf das neue Schema (`/c/<id>-slug>`) ist das Problem gelöst.
Ursache war, dass NextJS hat das serverseitige abrufen der Daten (über [App#getInitialProps](https://nextjs.org/docs/pages/api-reference/functions/get-initial-props)) abgebrochen hat, wenn zwei Weiterleitungen (wie in diesem Fall Seite → /categories/123 → /c/123) schnell hintereinander gestartet wurden. Ich gehe davon aus, dass der Fehler durch das Update der Next-Version zustande kam.

Grundsätzlich möchten wir ja auch – wie schon für den Admin-Bereich geschehen – sukzessive auf den [App Router](https://nextjs.org/docs/app) umstellen, der uns eine deutlich bessere Kontrolle über das Vorladen von Daten für bestimmte Seitenbereiche ermöglicht. Ich würde hier also ungern viel mehr Energie als auf Symptom-Bekämpfung legen, wenn es keine größeren Probleme gibt.

Ich habe alle Instanzen nach weiteren Links in einem alternativen Format durchsucht und konnte keine finden.
Sollte das Problem tatsächlich bei anderen Instanzen (unter ähnlichen?) Umständen (in ähnlicher Weise?) vorkommen, bitte ein neues Ticket aufmachen und Details zum reproduzieren hinzufügen. Es handelt sich vermutlich um ein anderes Problem. Als Minimum bitte URL unter der die Fehlermeldung und Browser aufführen (einfach die Felder in der Vorlage ausfüllen).
Ohne weitere Infos kann ich nicht mehr als einen simplen Klicktest machen, der bei mir keine Probleme verursacht.
