### ISSUE TITLE
Beitragseite: Bildmodul: Safari zeigt Bilder zu groß an so dass sie in der Breite abgeschnitten wirken

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#392]
### Bug-Beschreibung

Einzelbilder im Bildmodul werden am rechten Rand angeschnitten. Das Bildmodul sollte sich der Größe der Bildes anpassen. 
<img width="1606" alt="Bildschirmfoto 2024-10-01 um 20 46 23" src="https://github.com/user-attachments/assets/0ca08474-0940-43c9-bedd-d6967dd9eb4f">

### Link zur Seite, auf der das Problem aufgefallen ist

https://inklusivleben.jetzt/a/265-...-im-September

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
@wie0815 Bitte in Zukunft Browser mit angeben, dann muss ich nicht drei verschiedene ausprobieren bevor ich das Problem nachstellen kann.
