### ISSUE TITLE
[Bug]: Mehrtägige Termine werden nicht korrekt angezeigt

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#398]
### Bug-Beschreibung

Die Termine sind nun auch in Google-Kalender sichtbar, doch werden mehrtägige Termine im Abonnement sowohl in Google-Kalender als auch in Kalender von Apple -1 Tag angezeigt. Es fehlt immer der letzte Tag. Vgl. A-Woche im öffentlichen Kalender von Ehrenberg in der 48. Kalenderwoche (25.-29.11.2024)

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/data/calendar/c25207de-279d-440e-a532-44defaf67357/ics

### Gerätekategorie

Trifft hier nicht zu

**Comment by ptitmouton** [comment]
Ich finde keine konklusiven Hinweise in der Dokumentation des Standards, ich gehe aber einfach davon aus dass `DTEND` wenn ein Tag ohne Uhrzeit übergeben wird das exklusive Ende meint.

Das würde bedeuten, dass immer `DTEND` immer das Datum *nach* dem letzten Tag des Ereignisses meinen würde.

Hab das entsprechend angepasst.
