### ISSUE TITLE
[Bug]: Das Filtern im Admin-Bereich: "Nutzer suchen" verbessern

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#402]
### Bug-Beschreibung

Filtert man z.B. nach Gruppen und gibt den korrekten Namen der Gruppe ein, wird dieser (in meinem Beispiel) nicht angezeigt. Das Auswahlfenster erschwert die Suche zusätzlich, da sie von einem weiteren Element verdeckt wird und nur ein kleiner Ausschnitt sichtbar ist (Issue wird im Anschluss erstellt.)
<img width="1059" alt="Bildschirmfoto 2024-10-23 um 09 54 17" src="https://github.com/user-attachments/assets/3b6a2790-628c-44d1-ae9c-c22155b30fd2">

https://github.com/user-attachments/assets/b2f94331-40c8-452b-ae38-248a05386695

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/admin/users

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by BillyTheKing** [comment]
duplicate: 
#148 
#357 
#333
