### ISSUE TITLE
[Bug]: Auswahlfenster im Admin-Bereich "Nutzer suchen" durch Designelement verdeckt

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#403]
### Bug-Beschreibung

Im Admin-Bereich "Nutzer suchen" wird das Auswahlfenster zum "Filtern nach Gruppen" und "Zuletzt angemeldet" durch ein Designelement verdeckt.
<img width="1059" alt="Bildschirmfoto 2024-10-23 um 09 54 17" src="https://github.com/user-attachments/assets/cc7902e5-83ee-48a2-976a-ee05ca850c9c">

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/admin/users

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
@wie0815 es geht nicht schneller wenn du das gleiche Ticket mehrmals aufmachst. Im Gegenteil. Tickets bearbeiten ist ein Riesen Aufwand, es ist nicht notwendig uns zusätzlich Stöcke in die Räder zu werfen. 

Dieses Problem wurde mittlerweile schon zum 5. Mal gemeldet:

duplicate:
#148
#357
#333
#402

Die Dringlichkeit ist hier dadurch genommen dass es nur Safari betrifft und Safari es eigentlich auch falsch macht. Wie in [diesem Kommentar](https://github.com/lotta-schule/lotta/issues/148#issuecomment-2318646899) zu dem Ticket, in dem die Sache besprochen wird, aber hoffentlich aus meiner Antwort ersichtlich wird, habe ich das Problem auf dem Schirm und möchte mich zur nächsten Version darum kümmern. Dazu ist aber ein grundsätzlicher Umbau unserer Overlays nötig und das könnte etwas heikel werden. 

Wenn du etwas *neues* zu der Problematik beisteuern möchtest tu das bitte in jenem Ticket und mach keine neuen mehr dazu auf.
Ansonsten lehn dich zurück es wird für dich repariert ;)
