### ISSUE TITLE
[Bug]: Kalenderabonnement: Anzeige fehlerhaft -1 Tag (in der Google-Kalender-App)

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#404]
### Bug-Beschreibung

Der ganztägige Termin "bt1, ge3+5, grw4+5" am 28.10.2024 wird korrekt in der Marginalen angezeigt. In der Google-Kalender-App wird es immer noch (länger als 24 Stunden nach Behebung unserer Bugs) einen Tag zu früh angezeigt am Sonntag, den 27.10.2024. Alle weiteren Termine im Kalender werden auch -1 Tag angezeigt.

### Gerätekategorie

Trifft hier nicht zu

**Comment by ptitmouton** [comment]
Duplikat von #399

/close

@wie0815 Google scheint sich die Eigenschaft DTSTAMP im Kalender anzusehen, die beschreibt wann der Kalender zuletzt bearbeitet wurde. 
Ich habe das nicht gewusst und deshalb versäumt sie mit dem Setzen der Zeitzone in #400 zu setzen. 
Das bedeutet einmal kurz einen Kalender (oder Termin) bearbeiten, dann sollte Google beim nächsten Update die Änderung annehmen. 

Ich übernehme das mal für die drei Kalender

PS: bitte keine sensiblen Daten bei github posten! Diese Kommunikation ist öffentlich
