### ISSUE TITLE
Kalender-Marginale: wiederholende Termine werden für den aktuellen Monat auch angezeigt wenn sie schon vergangen sind

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/lotta#411]
### Bug-Beschreibung

In der Kalender-Marginale werden lotta-eigene Termine, die als wiederholend eingestellt sind, für den aktuellen Monat auch dann angezeigt, wenn sie schon vorbei sind.

### Link zur Seite, auf der das Problem aufgefallen ist

https://info.lotta.schule/c/93-Finanzen

Der eingebundene Testkalender mit einem sich wiederholenden Termin, der am 03.10.2024 beginnt. Alle Termine für den aktuellen Monat (getestet: Am 21. November wurde der Termin von 14.11 angezeigt)

### Gerätekategorie

Auf Desktop getestet

### In welchem Browser ist das Problem aufgetreten

In Chrome getestet

**Comment by wie0815** [comment]
@ptitmouton Es ist wie beschrieben. Der Kalender, den ich auf Info.lotta.schule in der Kategorie "Finanzen" angelegt habe, zeigt aktuell den ersten Termin für den 14.11. an (der Tag, an dem ich den Kalender erstellt hatte).

**Comment by wie0815** [comment]
@BillyTheKing @ptitmouton Radebeul hat soeben nachgefragt. Es wäre schön, wenn wir das Problem zeitnah lösen könnten. LG

**Comment by ptitmouton** [comment]
@BillyTheKing Ich übernehme mal direkt
