### ISSUE TITLE
Größere Palette an Schriften für ein Lotta bereitstellen 

### ISSUE THREAD

**Issue by techotline** [lotta-schule/lotta#97]
Administrationsbereich (Darstellung)

Bisher: Derzeit kann der Kunde eines Lottas zwischen einer kleinen Auswahl an Schriften seine Überschrift sowie Fließtext konfigurieren. 

**Idee**: Zukünftig sollte man diese Palette erweitern, um dem Kunden mehr Möglichkeiten in der Gestaltung anzubieten und eine Varianz zwischen allen Lotta zu schaffen. 

Klickweg: Admin -> Darstellung -> Schriften

**Comment by techotline** [comment]
Frage: Könnten Admins eigene Schriften integrieren, um ihr Lotta zu gestalten?

**Comment by BillyTheKing** [comment]
@techotline Ein Hinzufügen von einer beliebigen Anzahl an Schriftarten ist nicht problemlos möglich. Neue Schriftarten anzubieten ist auf jeden Fall eine Überlegung wert, zumal die momentane Auswahl 2019 getroffen wurde.
Welche Schriftarten fehlen dir denn?

**Comment by techotline** [comment]
> @techotline Ein Hinzufügen von einer beliebigen Anzahl an Schriftarten ist nicht problemlos möglich. Neue Schriftarten anzubieten ist auf jeden Fall eine Überlegung wert, zumal die momentane Auswahl 2019 getroffen wurde. Welche Schriftarten fehlen dir denn?

z.B. siehe Screenshot:
<img width="384" alt="SC-Schrfiten" src="https://github.com/lotta-schule/web/assets/153733311/d4bb669f-da9f-4637-9983-89cdad69f356">

**Comment by techotline** [comment]
Kleiner Fehler meinerseits: "Krub" ist schon vorhanden. Stattdessen: "Comfortaa"

**Comment by BillyTheKing** [comment]
Dir geht es also primär um die Auswahl an Fonts für den Fließtext, wenn ich das richtig sehe. Und zudem vornehmlich serifenlos.
Arial – klarer Veto. Krub bieten wir aktuell sogar an. Bei dem Rest werde ich das Schriftbild überprüfen und dann entscheiden wir welche neuen Schriftarten hinzukommen 👍

**Comment by techotline** [comment]
> Dir geht es also primär um die Auswahl an Fonts für den Fließtext, wenn ich das richtig sehe. Und zudem vornehmlich serifenlos. Arial – klarer Veto. Krub bieten wir aktuell sogar an. Bei dem Rest werde ich das Schriftbild überprüfen und dann entscheiden wir welche neuen Schriftarten hinzukommen 👍

Ich würde mich ungern auf den Fleißtext beschränken. 

Tatsächlich finde ich, dass Serienschriften für Schulen ungeeignet sind, weil A) Das Schreiben wird so nicht gelehrt B) Vereinzelt werden Zeichen (wie "T", "E / e", "g" oder "z") nicht so dargestellt, um für alle Anwendungen kompatibel zu sein (Praktikabilität)!

Arial = ok! 
Können wir gerne durch Cambria ersetzen (als Serife für Fließtext). **Hast Du Ideen für weitere Überschriften?**

**Comment by ptitmouton** [comment]
Für Schriftvorschläge brauchen wir eine Liste der Vorschläge als Text (nicht Screenshot) mit einer Info über die Lizenz (können nur lizenzfreie Schriften nehmen, was Arial unabhängig von Qualität und Ruf ausschließt) und am Besten ein Link zu Google Fonts falls verfügbar (falls nicht ist es ja schonmal ein guter Hinweis darauf dass die Schrift nicht frei ist)

Das können wir dann als Diskussionsbasis nutzen (cc @wie0815 )

**Comment by techotline** [comment]
> Für Schriftvorschläge brauchen wir eine Liste der Vorschläge als Text (nicht Screenshot) mit einer Info über die Lizenz (können nur lizenzfreie Schriften nehmen, was Arial unabhängig von Qualität und Ruf ausschließt) und am Besten ein Link zu Google Fonts falls verfügbar (falls nicht ist es ja schonmal ein guter Hinweis darauf dass die Schrift nicht frei ist)
> 
> Das können wir dann als Diskussionsbasis nutzen (cc @wie0815 )

Geht klar. Ich werde die Vorschläge zusammenführen und auf deren Verfügbarkeit prüfen. 😃

**Comment by techotline** [comment]
Neue Vorschläge, da Lizenzen nicht verfügbar! 

**Vorschläge Fließtext:** 

- [ ] Roboto | https://fonts.google.com/specimen/Roboto
- [ ] Comfortaa | https://fonts.google.com/specimen/Comfortaa?query=comfo
- [ ] Inter | https://fonts.google.com/specimen/Inter
- [ ] Raleway: https://fonts.google.com/specimen/Raleway
- [ ] Nunito | https://fonts.google.com/specimen/Nunito
- [ ] Exo 2 | https://fonts.google.com/specimen/Exo+2
- [ ] Titillium Web | https://fonts.google.com/specimen/Titillium+Web

**Vorschlag Überschriften:** 

- [ ] Indie Flower | https://fonts.google.com/specimen/Indie+Flower?classification=Display,Handwriting
- [ ] Shadows Into Light | https://fonts.google.com/specimen/Shadows+Into+Light
- [ ] Caveat | https://fonts.google.com/specimen/Caveat

**Comment by BillyTheKing** [comment]
@techotline Danke für deine Mühe.
Robot, Inter, Nunito sehe ich für Fließtext als möglich an.

**Comment by techotline** [comment]
> @techotline Danke für deine Mühe.
> 
> Roboto, Inter, Nunito sehe ich für Fließtext als möglich an. 

@BillyTheKing Nicht dafür! Das sind meine Ideen und die möchte ich gerne teilen. Ich danke Euch! #Schriften schön zu hören.

**Comment by ptitmouton** [comment]
Roboto ist doch die Hausschrift von Google? 😄 

Hat der Kunstlehrer auch eine Meinung zu Schriften @wie0815 ?

Mir fällt noch ein es wäre auch gut zu prüfen dass alle Umlaute können

**Comment by wie0815** [comment]
Grundsätzlich finde ich eine größere Auswahl sinnvoll. Gerne mehr!

**Comment by ptitmouton** [comment]
Wie ist hier der Stand?
Wollen wir das weiter verfolgen? @BillyTheKing @wie0815 
Werden noch Schriften gesammelt oder soll es bei den 3 Schriften bleiben? @techotline

**Comment by techotline** [comment]
@ptitmouton Danke für Deine Erinnerung. Drei neue Schriften einzuführen, finde ich für das Ticket etwas zu aufwendig. Es sollte sich lohnen, darin Arbeit zu investieren. Ich hätte zeitnah noch weitere beigesteuert, würde mich jedoch über Input von @wie0815 freuen!

Er hat ein gutes Auge.

**Comment by wie0815** [comment]
Eine größere Auswahl an Schriften wäre wünschenswert. Bin für eine Begrenzung auf max. 8-10 Schriften. Dabei sollten Überschriften und Lauftext verschiedene Schriftarten anbieten.

**Comment by techotline** [comment]
Weitere Resultate als Diskussionsvorlage:

- [ ] [Cairo](https://fonts.google.com/specimen/Cairo?preview.text=Das%20ist%20ein%20wunderbarer%20Tag%20@%2F%2F(%22%22)%22ZWSH¶¢%5B%5D%7C%7B%7D≠‚∂ƒ©ªºµµœöäßöäü…∞–∞åµ~∫√çƒ∂%3D-%2B§$%25%26%2F()ASDCVBNM~∫√ç∂‚∑«“¶¢%5B%5D%7C%7B%5D%5B¢€„“%22“¶%5D%7C%7B%E2%81%84øπ•æåµ~≈∫≈∫~µ∞…å–•“¡¿¿≠%7D“%7C%5D%5B¢¶“””%23æ@‚∆•πø«@œœ•πœæ@∆π•±æœ–…∞%E2%81%84ø∆ºµ∞@œæ‘‘‘‘‘‘‘‘‘‘±±•πø≠¿¿%27…–…œ@∆%E2%81%84øπ•±æ–∞µ~∫√√ç∂ƒ©ºº∆@ø%E2%81%84%E2%81%84¨%7D≠¿%27%27•±±±±±±±±±±±±±%27±‘æœ@∆ºª©ƒ∂≈ç%E2%80%BA˘˛˛˘%E2%80%BA%E2%80%BA˘%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%BA˘˘ﬂŒŒŒŒ∏∏ØØÆÆŒÆﬂØÛÛÁˇÁÛØ∏°°•æœ∆@ø¿≠%7D%E2%81%84¨ºª∫««∑∑€€®®«å‚««««««&query=Cairo)
- [ ] [Shantell Sans](https://fonts.google.com/specimen/Shantell+Sans?preview.text=Das%20ist%20ein%20wunderbarer%20Tag%20@%2F%2F(%22%22)%22ZWSH¶¢%5B%5D%7C%7B%7D≠‚∂ƒ©ªºµµœöäßöäü…∞–∞åµ~∫√çƒ∂%3D-%2B§$%25%26%2F()ASDCVBNM~∫√ç∂‚∑«“¶¢%5B%5D%7C%7B%5D%5B¢€„“%22“¶%5D%7C%7B%E2%81%84øπ•æåµ~≈∫≈∫~µ∞…å–•“¡¿¿≠%7D“%7C%5D%5B¢¶“””%23æ@‚∆•πø«@œœ•πœæ@∆π•±æœ–…∞%E2%81%84ø∆ºµ∞@œæ‘‘‘‘‘‘‘‘‘‘±±•πø≠¿¿%27…–…œ@∆%E2%81%84øπ•±æ–∞µ~∫√√ç∂ƒ©ºº∆@ø%E2%81%84%E2%81%84¨%7D≠¿%27%27•±±±±±±±±±±±±±%27±‘æœ@∆ºª©ƒ∂≈ç%E2%80%BA˘˛˛˘%E2%80%BA%E2%80%BA˘%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%BA˘˘ﬂŒŒŒŒ∏∏ØØÆÆŒÆﬂØÛÛÁˇÁÛØ∏°°•æœ∆@ø¿≠%7D%E2%81%84¨ºª∫««∑∑€€®®«å‚««««««&preview.size=29&classification=Handwriting)
- [ ] [Courier Prime](https://fonts.google.com/specimen/Courier+Prime?preview.text=%20Das%20ist%20ein%20wunderbarer%20Tag%20@%2F%2F(%22%22)%22ZWSH¶¢%5B%5D%7C%7B%7D≠‚∂ƒ©ªºµµœöäßöäü…∞–∞åµ~∫√çƒ∂%3D-%2B§$%25%26%2F()ASDCVBNM~∫√ç∂‚∑«“¶¢%5B%5D%7C%7B%5D%5B¢€„“%22“¶%5D%7C%7B%E2%81%84øπ•æåµ~≈∫≈∫~µ∞…å–•“¡¿¿≠%7D“%7C%5D%5B¢¶“””%23æ@‚∆•πø«@œœ•πœæ@∆π•±æœ–…∞%E2%81%84ø∆ºµ∞@œæ‘‘‘‘‘‘‘‘‘‘±±•πø≠¿¿%27…–…œ@∆%E2%81%84øπ•±æ–∞µ~∫√√ç∂ƒ©ºº∆@ø%E2%81%84%E2%81%84¨%7D≠¿%27%27•±±±±±±±±±±±±±%27±‘æœ@∆ºª©ƒ∂≈ç%E2%80%BA˘˛˛˘%E2%80%BA%E2%80%BA˘%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%BA˘˘ﬂŒŒŒŒ∏∏ØØÆÆŒÆﬂØÛÛÁˇÁÛØ∏°°•æœ∆@ø¿≠%7D%E2%81%84¨ºª∫««∑∑€€®®«å‚««««««&preview.size=29&query=reen)
- [ ] [Farsan](https://fonts.google.com/specimen/Farsan?preview.text=Das%20ist%20ein%20wunderbarer%20Tag%20äöü@%2F%2F(%22%22)%22ZWSH¶¢%5B%5D%7C%7B%7D≠‚∂ƒ©ªºµµœöäßöäü…∞–∞åµ~∫√çƒ∂%3D-%2B§$%25%26%2F()ASDCVBNM~∫√ç∂‚∑«“¶¢%5B%5D%7C%7B%5D%5B¢€„“%22“¶%5D%7C%7B%E2%81%84øπ•æåµ~≈∫≈∫~µ∞…å–•“¡¿¿≠%7D“%7C%5D%5B¢¶“””%23æ@‚∆•πø«@œœ•πœæ@∆π•±æœ–…∞%E2%81%84ø∆ºµ∞@œæ‘‘‘‘‘‘‘‘‘‘±±•πø≠¿¿%27…–…œ@∆%E2%81%84øπ•±æ–∞µ~∫√√ç∂ƒ©ºº∆@ø%E2%81%84%E2%81%84¨%7D≠¿%27%27•±±±±±±±±±±±±±%27±‘æœ@∆ºª©ƒ∂≈ç%E2%80%BA˘˛˛˘%E2%80%BA%E2%80%BA˘%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%BA˘˘ﬂŒŒŒŒ∏∏ØØÆÆŒÆﬂØÛÛÁˇÁÛØ∏°°•æœ∆@ø¿≠%7D%E2%81%84¨ºª∫««∑∑€€®®«å‚««««««&preview.size=29&classification=Handwriting)
- [ ] [Dosis](https://fonts.google.com/specimen/Dosis?preview.text=Das%20ist%20ein%20wunderbarer%20Tag%20@%2F%2F(%22%22)%22ZWSH¶¢%5B%5D%7C%7B%7D≠‚∂ƒ©ªºµµœöäßöäü…∞–∞åµ~∫√çƒ∂%3D-%2B§$%25%26%2F()ASDCVBNM~∫√ç∂‚∑«“¶¢%5B%5D%7C%7B%5D%5B¢€„“%22“¶%5D%7C%7B%E2%81%84øπ•æåµ~≈∫≈∫~µ∞…å–•“¡¿¿≠%7D“%7C%5D%5B¢¶“””%23æ@‚∆•πø«@œœ•πœæ@∆π•±æœ–…∞%E2%81%84ø∆ºµ∞@œæ‘‘‘‘‘‘‘‘‘‘±±•πø≠¿¿%27…–…œ@∆%E2%81%84øπ•±æ–∞µ~∫√√ç∂ƒ©ºº∆@ø%E2%81%84%E2%81%84¨%7D≠¿%27%27•±±±±±±±±±±±±±%27±‘æœ@∆ºª©ƒ∂≈ç%E2%80%BA˘˛˛˘%E2%80%BA%E2%80%BA˘%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%BA˘˘ﬂŒŒŒŒ∏∏ØØÆÆŒÆﬂØÛÛÁˇÁÛØ∏°°•æœ∆@ø¿≠%7D%E2%81%84¨ºª∫««∑∑€€®®«å‚««««««&query=dosis)
- [ ] [Protest Revolution](https://fonts.google.com/specimen/Protest+Revolution?preview.text=%20Das%20ist%20ein%20wunderbarer%20Tag%20@%2F%2F(%22%22)%22ZWSH¶¢%5B%5D%7C%7B%7D≠‚∂ƒ©ªºµµœöäßöäü…∞–∞åµ~∫√çƒ∂%3D-%2B§$%25%26%2F()ASDCVBNM~∫√ç∂‚∑«“¶¢%5B%5D%7C%7B%5D%5B¢€„“%22“¶%5D%7C%7B%E2%81%84øπ•æåµ~≈∫≈∫~µ∞…å–•“¡¿¿≠%7D“%7C%5D%5B¢¶“””%23æ@‚∆•πø«@œœ•πœæ@∆π•±æœ–…∞%E2%81%84ø∆ºµ∞@œæ‘‘‘‘‘‘‘‘‘‘±±•πø≠¿¿%27…–…œ@∆%E2%81%84øπ•±æ–∞µ~∫√√ç∂ƒ©ºº∆@ø%E2%81%84%E2%81%84¨%7D≠¿%27%27•±±±±±±±±±±±±±%27±‘æœ@∆ºª©ƒ∂≈ç%E2%80%BA˘˛˛˘%E2%80%BA%E2%80%BA˘%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%BA˘˘ﬂŒŒŒŒ∏∏ØØÆÆŒÆﬂØÛÛÁˇÁÛØ∏°°•æœ∆@ø¿≠%7D%E2%81%84¨ºª∫««∑∑€€®®«å‚««««««&preview.size=29&classification=Display)
- [ ] [Old Standard TT](https://fonts.google.com/specimen/Old+Standard+TT?preview.text=%20Das%20ist%20ein%20wunderbarer%20Tag%20@%2F%2F(%22%22)%22ZWSH¶¢%5B%5D%7C%7B%7D≠‚∂ƒ©ªºµµœöäßöäü…∞–∞åµ~∫√çƒ∂%3D-%2B§$%25%26%2F()ASDCVBNM~∫√ç∂‚∑«“¶¢%5B%5D%7C%7B%5D%5B¢€„“%22“¶%5D%7C%7B%E2%81%84øπ•æåµ~≈∫≈∫~µ∞…å–•“¡¿¿≠%7D“%7C%5D%5B¢¶“””%23æ@‚∆•πø«@œœ•πœæ@∆π•±æœ–…∞%E2%81%84ø∆ºµ∞@œæ‘‘‘‘‘‘‘‘‘‘±±•πø≠¿¿%27…–…œ@∆%E2%81%84øπ•±æ–∞µ~∫√√ç∂ƒ©ºº∆@ø%E2%81%84%E2%81%84¨%7D≠¿%27%27•±±±±±±±±±±±±±%27±‘æœ@∆ºª©ƒ∂≈ç%E2%80%BA˘˛˛˘%E2%80%BA%E2%80%BA˘%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%BA˘˘ﬂŒŒŒŒ∏∏ØØÆÆŒÆﬂØÛÛÁˇÁÛØ∏°°•æœ∆@ø¿≠%7D%E2%81%84¨ºª∫««∑∑€€®®«å‚««««««&preview.size=29&classification=Display&query=Old+St)
- [ ] [Unkempt](https://fonts.google.com/specimen/Unkempt?preview.text=Das%20ist%20ein%20wunderbarer%20Tag%20äöü.,s%20@%2F%2F(%22%22)%22ZWSH¶¢%5B%5D%7C%7B%7D≠‚∂ƒ©ªºµµœöäßöäü…∞–∞åµ~∫√çƒ∂%3D-%2B§$%25%26%2F()ASDCVBNM~∫√ç∂‚∑«“¶¢%5B%5D%7C%7B%5D%5B¢€„“%22“%5E¶%5D%7C%7B%E2%81%84øπ•æåµ~≈∫≈∫~µ∞…å–•“¡¿¿≠%7D“%7C%5D%5B¢¶“””%23æ@‚∆•πø«@œœ•πœæ@∆π•±æœ–…∞%E2%81%84ø∆ºµ∞@œæ‘‘‘‘‘‘‘‘‘‘±±•πø≠¿¿%27…–…œ@∆%E2%81%84øπ•±æ–∞µ~∫√√ç∂ƒ©ºº∆@ø%E2%81%84%E2%81%84¨%7D≠¿%27%27•±±±±±±±±±±±±±%27±‘æœ@∆ºª©ƒ∂≈ç%E2%80%BA˘˛˛˘%E2%80%BA%E2%80%BA˘%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%BA˘˘ﬂŒŒŒŒ∏∏ØØÆÆŒÆﬂØÛÛÁˇÁÛØ∏°°•æœ∆@ø¿≠%7D%E2%81%84¨ºª∫««∑∑€€®®«å‚««««««)
- [ ] [Afacad](https://fonts.google.com/specimen/Afacad?sort=date&preview.text=Das%20ist%20ein%20wunderbarer%20Tag%20@%2F%2F(%22%22)%22ZWSH¶¢%5B%5D%7C%7B%7D≠‚∂ƒ©ªºµµœöäßöäü…∞–∞åµ~∫√çƒ∂%3D-%2B§$%25%26%2F()ASDCVBNM~∫√ç∂‚∑«“¶¢%5B%5D%7C%7B%5D%5B¢€„“%22“¶%5D%7C%7B%E2%81%84øπ•æåµ~≈∫≈∫~µ∞…å–•“¡¿¿≠%7D“%7C%5D%5B¢¶“””%23æ@‚∆•πø«@œœ•πœæ@∆π•±æœ–…∞%E2%81%84ø∆ºµ∞@œæ‘‘‘‘‘‘‘‘‘‘±±•πø≠¿¿%27…–…œ@∆%E2%81%84øπ•±æ–∞µ~∫√√ç∂ƒ©ºº∆@ø%E2%81%84%E2%81%84¨%7D≠¿%27%27•±±±±±±±±±±±±±%27±‘æœ@∆ºª©ƒ∂≈ç%E2%80%BA˘˛˛˘%E2%80%BA%E2%80%BA˘%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%BA˘˘ﬂŒŒŒŒ∏∏ØØÆÆŒÆﬂØÛÛÁˇÁÛØ∏°°•æœ∆@ø¿≠%7D%E2%81%84¨ºª∫««∑∑€€®®«å‚««««««)
- [ ] [Kodchasan](https://fonts.google.com/specimen/Kodchasan?sort=date&preview.text=Das%20ist%20ein%20wunderbarer%20Tag%20@%2F%2F(%22%22)%22ZWSH¶¢%5B%5D%7C%7B%7D≠‚∂ƒ©ªºµµœöäßöäü…∞–∞åµ~∫√çƒ∂%3D-%2B§$%25%26%2F()ASDCVBNM~∫√ç∂‚∑«“¶¢%5B%5D%7C%7B%5D%5B¢€„“%22“¶%5D%7C%7B%E2%81%84øπ•æåµ~≈∫≈∫~µ∞…å–•“¡¿¿≠%7D“%7C%5D%5B¢¶“””%23æ@‚∆•πø«@œœ•πœæ@∆π•±æœ–…∞%E2%81%84ø∆ºµ∞@œæ‘‘‘‘‘‘‘‘‘‘±±•πø≠¿¿%27…–…œ@∆%E2%81%84øπ•±æ–∞µ~∫√√ç∂ƒ©ºº∆@ø%E2%81%84%E2%81%84¨%7D≠¿%27%27•±±±±±±±±±±±±±%27±‘æœ@∆ºª©ƒ∂≈ç%E2%80%BA˘˛˛˘%E2%80%BA%E2%80%BA˘%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%BA˘˘ﬂŒŒŒŒ∏∏ØØÆÆŒÆﬂØÛÛÁˇÁÛØ∏°°•æœ∆@ø¿≠%7D%E2%81%84¨ºª∫««∑∑€€®®«å‚««««««)
- [ ] [GFS Neohellenic](https://fonts.google.com/specimen/GFS+Neohellenic?sort=date&preview.text=Das%20ist%20ein%20wunderbarer%20Tagäöü%20@%2F%2F(%22%22)%22ZWSH¶¢%5B%5D%7C%7B%7D≠‚∂ƒ©ªºµµœöäßöäü…∞–∞åµ~∫√çƒ∂%3D-%2B§$%25%26%2F()ASDCVBNM~∫√ç∂‚∑«“¶¢%5B%5D%7C%7B%5D%5B¢€„“%22“¶%5D%7C%7B%E2%81%84øπ•æåµ~≈∫≈∫~µ∞…å–•“¡¿¿≠%7D“%7C%5D%5B¢¶“””%23æ@‚∆•πø«@œœ•πœæ@∆π•±æœ–…∞%E2%81%84ø∆ºµ∞@œæ‘‘‘‘‘‘‘‘‘‘±±•πø≠¿¿%27…–…œ@∆%E2%81%84øπ•±æ–∞µ~∫√√ç∂ƒ©ºº∆@ø%E2%81%84%E2%81%84¨%7D≠¿%27%27•±±±±±±±±±±±±±%27±‘æœ@∆ºª©ƒ∂≈ç%E2%80%BA˘˛˛˘%E2%80%BA%E2%80%BA˘%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%BA%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%B9%E2%80%BA˘˘ﬂŒŒŒŒ∏∏ØØÆÆŒÆﬂØÛÛÁˇÁÛØ∏°°•æœ∆@ø¿≠%7D%E2%81%84¨ºª∫««∑∑€€®®«å‚««««««)

letzter Abruf: 2024-02-04 18:23

@ptitmouton Umlaute + Sonderzeichen sind bei den 11 Schriften geprüft. Beides weitesgehend möglich.

> Roboto ist doch die Hausschrift von Google? 😄

... korrekt, Roboto ist die Hausschrift von Google. Bist Du für eine Aufnahme ins eigene Repertoire?

@wie0815 konstruktives Argument! -> Die Schriften sollten getrennt voneinander behandelt werden.  Aktuell werden vereinzelt der Pool aus Überschriften und Fließtext "gemixt". D.h., eine Überschrift sollte nicht gleichzeitig als Fließtext fungieren können. @ptitmouton @BillyTheKing

**Comment by ptitmouton** [comment]
Wie ist hier der Plan @BillyTheKing @wie0815 

Ich würde das Ticket eigentlich gerne mal zum Abschluss bringen.
Kann sich da mal bitte jemand äußern der Ahnung von Typographie hat, ob wir mehr Schriften brauchen und wenn ja ob die Vorschläge gut sind?

Mir ist das ehrlich gesagt recht egal.

**Comment by wie0815** [comment]
Meine Meinung hatte ich schon 2x kundgetan. Ich denke @BillyTheKing sollte entscheiden, welche Schrift für A: Überschriften und/oder B für Fließtext Verwendung finden soll. Eine größere Auswahl ist gut und lässt den Lotta-Kunden mehr Spielraum bei der Gestaltung. Ich möchte mich nicht auf eine Zahl festlegen. Wenn es erste einmal 3 Schriftarten sind, auch gut. Wir können ja ggf. immer noch später Schriftarten hinzufügen.

**Comment by ptitmouton** [comment]
> Meine Meinung hatte ich schon 2x kundgetan.

Du hast dich zu keiner einzigen Schrift geäußert. Es geht hier darum eine Entscheidung zu treffen. Wäre schön wenn am Ende nicht alles bei mir hängen bleibt. 

Ich denke nicht dass Aufwand und Nutzen in Relation stehen, wenn wir jeden Monat die Schriften austauschen.

Heißt das, @BillyTheKing du entscheidest das jetzt?

**Comment by BillyTheKing** [comment]
@ptitmouton ich füge eine erweiterte Auswahl hinzu

**Comment by BillyTheKing** [comment]
Neue Schriftarten:
- https://fonts.google.com/specimen/Nunito
- https://fonts.google.com/specimen/Inter
- https://fonts.google.com/specimen/Teachers
- https://fonts.google.com/specimen/Assistant
- https://fonts.google.com/specimen/Ibarra+Real+Nova
- https://fonts.google.com/specimen/Cormorant?stroke=Serif

Neue Schriftarten **nur für Überschriften**: 
- https://fonts.google.com/specimen/Cormorant+SC?stroke=Serif
- https://fonts.google.com/specimen/Grandstander
